server:
  port: 8002

spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: book-management-group
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: jdbc:postgresql://postgres:5432/library
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db_migration